- name: install python-apt
  apt:
    name: python-apt
    update_cache: yes
  become: yes

- name: install vim
  apt:
    name: vim
    update_cache: yes
  become: yes

- name: install libevent
  apt:
    name: libevent-dev
    update_cache: yes
  become: yes

- name: install libncurses
  apt:
    name: libncurses-dev
    update_cache: yes
  become: yes

- name: install pkg-config
  apt:
    name: pkg-config
    update_cache: yes
  become: yes

- name: install tmux
  apt:
    name: tmux
    update_cache: yes
  become: yes
